# 13. Reshape Function - will not alter the original data

In [14]:
import numpy as np

In [16]:
arr = np.random.randint(1,15,(3,4))

print(arr.shape)
print(arr)
arr = arr.reshape(4,3)
print(arr)
print(arr.shape)

(3, 4)
[[ 2 12  1  7]
 [ 1  1 12  8]
 [13 13  4  3]]
[[ 2 12  1]
 [ 7  1  1]
 [12  8 13]
 [13  4  3]]
(4, 3)


# 14. Linspace Function

In [18]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

# 15. Flatten Function

In [36]:
arr = np.random.randint(1,15,(3,4))

print(arr.shape)
print(arr)
arr = arr.flatten()
print(arr.shape)
print(arr)

(3, 4)
[[14  9  4  6]
 [ 9  5  5  6]
 [ 2  5 11  5]]
(12,)
[14  9  4  6  9  5  5  6  2  5 11  5]


# 16. LogSpace Function

In [20]:
print(np.logspace(2,4, 10))

print("-"* 20)

print(np.logspace(2,4,10, base = 2))

[  100.           166.81005372   278.25594022   464.15888336
   774.26368268  1291.54966501  2154.43469003  3593.8136638
  5994.84250319 10000.        ]
--------------------
[ 4.          4.66611616  5.44316     6.34960421  7.4069977   8.64047791
 10.0793684  11.75787594 13.71590373 16.        ]


# 17. Copy Function

In [22]:
arr1 = np.random.randint(1,15,10)

arr2 = arr1

print(arr1, id(arr1))
print(arr2, id(arr2))

print("-"*50)

arr1 = np.random.randint(1,15,10)
arr2 = np.copy(arr1)

print(arr1, id(arr1))
print(arr2, id(arr2))


[12  2  9 11  4  9  6 13  3  4] 5560850000
[12  2  9 11  4  9  6 13  3  4] 5560850000
--------------------------------------------------
[11  3  2 14  5 14  3  5  5  9] 5560846160
[11  3  2 14  5 14  3  5  5  9] 5560859696


# 18. arr.max(), arr.min(), arr.sum() Functions

In [24]:
arr = np.random.randint(1,15,(3,5))

print("-"*30)
print(arr)
print("-"*30)

print("Max:", arr.max())
print("Min:", arr.min())
print("Sum:", arr.sum())


------------------------------
[[ 9  1  5 11  4]
 [ 1  9  8  3 13]
 [14  8  5  4  7]]
------------------------------
Max: 14
Min: 1
Sum: 102


# Axis Parameter to get max, min, sum Functions() 

In [26]:
print("Max:", arr.max( axis = 0 ))
print("Min:", arr.min( axis = 0 ))
print("Sum:", arr.sum( axis = 0))

# Axis 0 for the max,min,sum in each column
print("_"*30)

print("Max:", arr.max( axis = 1 ))
print("Min:", arr.min( axis = 1 ))
print("Sum:", arr.sum( axis = 1))

# Axis 1 for the max,min,sum in each row

Max: [14  9  8 11 13]
Min: [1 1 5 3 4]
Sum: [24 18 18 18 24]
______________________________
Max: [11 13 14]
Min: [1 1 4]
Sum: [30 34 38]


# 19. Seed Function

In [28]:
np.random.seed(3)

arr = np.random.randint(1,10,(3,5))

print(arr)

[[9 4 9 9 1]
 [6 4 6 8 7]
 [1 5 8 9 2]]


# 20. Sort Function

In [30]:
np.random.seed(3)
arr = np.random.randint(1,10,(3,5))

print("-"*15)
print(arr)
print("-"*15)
print(np.sort(arr, axis =1))
print("-"*15)
print(np.sort(arr,axis = 0))
print("-"*15)

arr = np.reshape(np.sort(arr.flatten()), arr.shape)
print(arr)
print("-"*15)


---------------
[[9 4 9 9 1]
 [6 4 6 8 7]
 [1 5 8 9 2]]
---------------
[[1 4 9 9 9]
 [4 6 6 7 8]
 [1 2 5 8 9]]
---------------
[[1 4 6 8 1]
 [6 4 8 9 2]
 [9 5 9 9 7]]
---------------
[[1 1 2 4 4]
 [5 6 6 7 8]
 [8 9 9 9 9]]
---------------


# We can choose which type of sort we want to perform

In [32]:
print(np.sort(arr, axis  = 0, kind= "mergesort"))

[[1 1 2 4 4]
 [5 6 6 7 8]
 [8 9 9 9 9]]


# 20. Mathematical Operations

In [34]:
# addition
np.random.seed(3)

arr = np.random.randint(1,10,(3,5))

print("-"*15)
print(arr)
print("-"*15)
print(arr+1)
print("-"*15)




---------------
[[9 4 9 9 1]
 [6 4 6 8 7]
 [1 5 8 9 2]]
---------------
[[10  5 10 10  2]
 [ 7  5  7  9  8]
 [ 2  6  9 10  3]]
---------------


In [36]:
# subtraction

print("-"*15)
print(arr)
print("-"*15)
print(arr - 1)
print("-"*15)

---------------
[[9 4 9 9 1]
 [6 4 6 8 7]
 [1 5 8 9 2]]
---------------
[[8 3 8 8 0]
 [5 3 5 7 6]
 [0 4 7 8 1]]
---------------


In [40]:
# multiply
print("-"*15)
print(arr)
print("-"*15)
print(arr*2)
print("-"*15)

---------------
[[7 3 3 2 4]
 [6 9 2 9 8]
 [9 2 1 6 5]]
---------------
[[14  6  6  4  8]
 [12 18  4 18 16]
 [18  4  2 12 10]]
---------------


In [101]:
# Divison

print("-"*15)
print(arr)
print("-"*15)
print(arr // 2)
print("-"*15)

---------------
[[9 4 9 9 1]
 [6 4 6 8 7]
 [1 5 8 9 2]]
---------------
[[4 2 4 4 0]
 [3 2 3 4 3]
 [0 2 4 4 1]]
---------------


In [121]:
# matrix multiplication

np.random.seed(3)

arr1 = np.random.randint(1,10,(2,2))
arr2  = np.random.randint(1,10,(2,2))

arr1
arr1.dot(arr2)

array([[ 25,  78],
       [ 45, 108]])

In [119]:
# Power

print(arr)
print("-"*15)
print(arr ** 2)

[[9 4 9 9 1]
 [6 4 6 8 7]
 [1 5 8 9 2]]
---------------
[[81 16 81 81  1]
 [36 16 36 64 49]
 [ 1 25 64 81  4]]


# 21. Percentile Function

In [126]:
np.random.seed(3)

arr = np.random.randint(1,10,10)
print(arr)

arr = np.sort(arr)
print(arr)

print(np.percentile(arr,50))

[9 4 9 9 1 6 4 6 8 7]
[1 4 4 6 6 7 8 9 9 9]
6.5


# 22. Mean, Variance and Standard Deviation

In [135]:
np.random.seed(3)

arr = np.random.randint(1,10,10)
print(arr)
print( "Mean:", arr.mean())
print("Std:",  arr.std())
print("Var", arr.var())

[9 4 9 9 1 6 4 6 8 7]
Mean: 6.3
Std: 2.5317977802344327
Var 6.410000000000001


# 23. Filtering an numpy array

In [144]:
arr = np.arange(1,10)

print(arr)
print(arr < 5)
arr2  = (arr[arr<5])
print(arr2)


[1 2 3 4 5 6 7 8 9]
[ True  True  True  True False False False False False]
[1 2 3 4]


In [150]:
# replace the value of 5 with 10

arr[arr>5] = 10
print(arr)

[ 1  2  3  4  5 10 10 10 10]


# 24. Transposing an array

In [153]:
arr = np.random.randint(1,20,(3,5))

print(arr)
print("-"*15)

print(arr.T)
print("-"*15)

[[ 1 13  8 15 18]
 [ 3  3  2  6  9]
 [15  2 11  8 12]]
---------------
[[ 1  3 15]
 [13  3  2]
 [ 8  2 11]
 [15  6  8]
 [18  9 12]]
---------------


# 25. Where Function

In [45]:
arr = np.random.randint(1,100,10)
arr

array([38, 57, 57, 72, 38, 47, 34,  2, 86, 75])

In [57]:
print(np.where(arr%2 == 0, 'even', arr))
print(np.where(arr%2 != 0, 'odd', arr))

arr1 = np.where(arr%2 == 0, 'even', arr)
arr1 = np.where(arr%2 != 0, 'odd', arr1)

print(arr1)

['even' '57' '57' 'even' 'even' '47' 'even' 'even' 'even' '75']
['38' 'odd' 'odd' '72' '38' 'odd' '34' '2' '86' 'odd']
['even' 'odd' 'odd' 'even' 'even' 'odd' 'even' 'even' 'even' 'odd']
