In [1]:
import numpy as np

# 1. Converting a List to Array

In [3]:
lst = [1,2,3,34,5,9]
print(type(lst))
np.array(lst)

<class 'list'>


array([ 1,  2,  3, 34,  5,  9])

In [4]:
type(np.array(lst))

numpy.ndarray

In [5]:
arr = np.array(lst, ndmin = 2)

In [6]:
arr

array([[ 1,  2,  3, 34,  5,  9]])

# 2. Arrange Function

In [8]:
np.arange(1,10,3)

array([1, 4, 7])

In [9]:
np.arange(1,20)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [10]:
for i in range(4,20,5):
    print(i)

4
9
14
19


# 3. Multidimensional Array

In [12]:
 arr = np.array([[2,3,4],[7,8,9],[45,66,43]])
arr

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [45, 66, 43]])

# 4.Size Function

In [14]:
arr = np.array([[1,2,3],[4,5,6],[93,9,20],[88,23,45]])

print("Total size: ", arr.size)
print("Rows:", np.size(arr,0))
print("Columns:", np.size(arr,1))

arr

Total size:  12
Rows: 4
Columns: 3


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [93,  9, 20],
       [88, 23, 45]])

In [15]:
arr.shape

(4, 3)

# 5. Shape Function

In [17]:
arr = np.array([[18,9,9],[43,3,55],[2,23,67]])

print((np.size(arr,0), np.size(arr,1)))
print(arr.shape)

(3, 3)
(3, 3)


# 6. Dtype Function

In [19]:
arr1 = np.array([18,9,9,23,90,20])
arr2 = np.array([1,2,3,4.5,6.9,7.0])
print(arr1.dtype)
print(arr2.dtype)

int64
float64


In [20]:
arr.dtype

dtype('int64')

# 7. Ndim Function

In [22]:
arr1 = np.array([1,2,3,9,7,8])
arr2 = np.array([[4,5,6],[23,34,45]])
print(arr1.ndim)
print(arr2.ndim)

arr3 = np.array(arr1, ndmin = 3)
print(arr3.ndim)

1
2
3


# 8. Zeros Function

In [24]:
arr = np.zeros(shape = (3,5), dtype = int )
print(arr)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


# 9. Ones Function

In [26]:
arr = np.ones(shape = (3,5), dtype = int)
print(arr)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


# 10. Eye Function

In [28]:
np.eye(5, dtype = int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

# 11. Empty Function

In [30]:
np.empty(shape = (5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# 12. Random Functions

In [32]:
np.random.rand(3,4)

array([[0.61142137, 0.93034353, 0.49602659, 0.52485587],
       [0.86322524, 0.39244927, 0.75511975, 0.56499214],
       [0.42098196, 0.58703958, 0.12035239, 0.54876186]])

In [33]:
np.random.randint(low = 10, high = 20, size = 10)

array([19, 11, 17, 11, 12, 17, 15, 16, 13, 18])

In [34]:
np.random.randn(100)

array([-0.29819955, -0.29599755,  1.16743607,  0.81233999, -1.61917016,
       -2.08809901,  0.19768533, -0.90444578,  0.77143104, -0.86980824,
        0.85729147, -1.5994258 ,  0.38127993, -0.28563875,  0.34131483,
       -0.11260412,  1.64082634, -1.708408  ,  1.8338424 ,  0.33353664,
        1.09348667, -1.66807621,  0.98671097, -0.60772524, -0.98891656,
       -0.98739328,  0.04038256, -0.87656898,  0.34690344, -1.03088171,
        0.90715714,  0.02580651,  0.7650057 , -1.08699784,  0.06450545,
       -0.30108729, -0.66796254,  0.46262892, -1.73112619, -0.07937609,
       -1.74434395, -2.23000964,  0.90598366,  1.38379539,  1.53000908,
        0.1784704 ,  0.64431043, -0.95391362, -1.61553783,  0.69901054,
        0.48050792, -1.66700666,  0.29457943,  0.0049966 , -0.7259509 ,
        0.73317826,  0.18376412,  0.42253858,  0.34337588, -0.99948296,
       -0.15115418,  1.24132648,  0.62992041,  0.40299639,  2.67922772,
        0.02442093, -1.55921197,  1.66168507,  0.81553139, -0.42

# 13. Reshape Function - will not alter the original data